### PR TITLE
Move to libpng via libpng_jll

### PR DESCRIPTION
**Pull request by IanButterworth**
Tests pass locally. Requires julia 1.3+

### CODE REVIEW

**Comment by IanButterworth** [comment]
Added Windows to Travis, and ARM64 linux. I left Appveyor for now to double-check.

And sorry, I just noticed #5 !

I'm actually working on libpng wrapping using a clang auto-generated wrapper (to catch all functions on offer), and this branch is helpful for my testing. I just thought it might be helpful.. so I'll leave this open for easy CI review, but happy for #5 to take priority :)

btw, thanks for all the work on this package! I'm trying to explore replacing ImageMagick.jl with direct lib integration, and this gives me hope! I'm borrowing code for now, but maybe the better plan would be to work the required standardized API into LibPNG.jl and release it?

**Comment by c42f** [comment]
I've been waiting on a `libpng_jll` tweak which would allow coexistence with < julia 1.3 before trying to push #5 further.

**Comment by c42f** [comment]
I updated #5 with the minimal change for julia 1.3 which should also be compatible with 1.2 if/when libpng_jll is updated upstream. I don't have a personal need for backward compat but figured it couldn't hurt.

I do agree that automatically wrapping the libpng API with clang is a good idea, and that working out a high level image IO API is helpful to do separately from a particular storage format (cf https://github.com/ianshmean/ImageIO.jl/issues/1)

**Comment by IanButterworth** [comment]
Great. I can put together a PR to LibPNG with my auto clang wrapped changes. It seems functional.

Might it be an idea to also move this to JuliaImages org or something, and rename it PNG.jl?

We could then make a JPEG.jl etc

**Comment by c42f** [comment]
I do think any widely used libpng wrapper should be managed from a community organization along with a few other key image libraries such as libjpeg. But I can't speak for the needs of the current owners of this repo regarding API compatibility requirements, deployment needs on pre-1.3 etc.

If you want to make sweeping changes to API and implementation it may be easier to just start a new repo (or fork+rename this one if the history is meaningful). What do you think, FugroRoames people?

**Comment by IanButterworth** [comment]
Oh! I just realized FugroRoames isn’t a person! 🤣

**Comment by IanButterworth** [comment]
Stale

**Pull request closed without merging**
